#!/bin/bash
export RuleNum=$(lynx -source -auth=admin:"$(cat /etc/netgear-password)" http://192.168.0.1/RgPortFiltering.asp|grep "PortBlockingActiveName.*value=\"$1\""|sed -e 's/.*PortBlockingActiveName//' -e 's/".*//')
echo "PortBlockingAction=2&PortBlockingSelectActiveIndex=$RuleNum" | lynx -source -post-data -auth=admin:$(cat /etc/netgear-password) http://192.168.0.1/goform/RgPortFiltering >/dev/null
