#!/bin/bash
COLUMNS=80 lynx -dump -auth=admin:"$(cat /etc/netgear-password)" http://192.168.0.1/RgSwInfo.asp|grep IP|grep -v '192\.168\.'|tail -1|sed -e 's/.* //'
# (tail -1 not usually necessary, but just in case.  ditto grep-out 192.168 IP addresses.)
